### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by icetooth-sketch** [anonieX/alienworldsauto#5]
Can you think of something with a random IP when a new window opens.
And so everything is really cool

**Comment by anonieX** [comment]
Brave has a Tor feature that sadly cannot be accessed by Selenium. You could use a VPN and set it only for Brave, if you are interested in that let me know. I would write a guide for it

**Comment by icetooth-sketch** [comment]
> Brave has a Tor feature that sadly cannot be accessed by Selenium. You could use a VPN and set it only for Brave, if you are interested in that let me know. I would write a guide for it

I have a vpn for brave, but running the script opens a browser without extensions, the guide would be very helpful, thanks

**Comment by anonieX** [comment]
I made [VPN.md](https://github.com/anonieX/alienworldsauto/blob/main/VPN.md). Let me know if it works. Thanks!
